I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 55, in script call
    call inventory
  File "game/script.rpy", line 55, in script call
    call inventory
ScriptError: could not find label 'inventory'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 55, in script call
    call inventory
  File "C:\Apps\Renpy\renpy-8.3.3-sdk\renpy\ast.py", line 1414, in execute
    rv = renpy.game.context().call(label, return_site=self.next.name)
  File "game/script.rpy", line 55, in script call
    call inventory
  File "C:\Apps\Renpy\renpy-8.3.3-sdk\renpy\script.py", line 1103, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'inventory'.

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.3.24111502
Simple Renpy Inventory 1.0
Tue Jan 14 18:57:15 2025
